# Martin Hazelton | The Future of Statistics at New Zealand Universities {-}

## Subsection 

Statistics is going a chaanging time Data scientist error

analytic, data science, data mining, machine learning etc

Budgetting of university and government

some ideas that statisticians value not necessary what some other believe

Less practical, loses competitive edge

rebranding carries a long time risk

buzz words

research assessment exercises (in UK)

PBRF funding (in NZ)

increase of staff in top universities, strengthern by ranking

but overall number of stats department and staff drops

diaspear in the pit of death /9less tha 6 staff)

University of Auckland is doing well

Hardly a panic situation, 

Challenges

low research profile
poor majoring numbers
honours trradtiotion way to get to PHD, 

Solutions?

more people from non-traditional background
data science is a oppontunity 

tragedy at waikato

had math stats CS, but did not build on that but became competitive bertween CS and stats







